### ISSUE TITLE
go-sysinfo repo cleanup meta-issue

### ISSUE THREAD

**Issue by fearful-symmetry** [elastic/go-sysinfo#60]
I'd like to track a few quality-of-life and codebase maintenance issues here, since I ran into a few things while trying to contribute to the code for the first time.

- [x] We need some makefiles to run basic Go things:  #61
  - [x] go-license 
  - [x] formatting
  - [x] goimports

- [x] A lot of files are missing godocs  #62
- [x] The tests are pretty neglected. After talking with @andrewkroh , it appears the solution is to pull out the ansible, replace it with vagrant setup scripts, and go from there.
